# Generated by Django 4.0.5 on 2022-08-26 05:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vehicleapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_eui', models.CharField(max_length=100)),
                ('parking_name', models.CharField(max_length=100)),
                ('platenumber', models.CharField(max_length=100)),
                ('checkin_date', models.DateTimeField(default=datetime.datetime.now)),
                ('checkout_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_checkout', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Show_v',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platenumber', models.CharField(max_length=9, unique=True, validators=[vehicleapi.models.validate_platenumber])),
                ('stateprovision', models.CharField(max_length=30)),
                ('modal', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleapi.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('price', models.IntegerField(default='30')),
                ('price_1hr', models.IntegerField(default='30')),
                ('no_of_parking', models.IntegerField(default='0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleapi.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_eui', models.CharField(max_length=100)),
                ('parking_name', models.CharField(max_length=100)),
                ('floor_no', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('lat', models.CharField(max_length=30)),
                ('lng', models.CharField(max_length=30)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='vehicleapi.parking_site')),
            ],
        ),
    ]
