# Generated by Django 4.0.5 on 2022-08-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='charge',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
